version: "3.8"

services:
  postgres:
    image: postgres
    volumes: 
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: Password123
    ports:
      - 5432:5432

volumes:
  db:
    driver: local