export const MCRM_ACCESS_TOKEN_KEY = 'MCRM_ACCESS_TOKEN';
export const MCRM_REFRESH_TOKEN_KEY = 'MCRM_REFRESH_TOKEN';
export const MCRM_APP_STORE_BACKUP = 'MCRM_APP_STORE_BACKUP';
export const MCRM_DARK_MODE = 'MCRM_DARK_MODE';
export const MCRM_QUERY_KEY_USERS = 'USERS';
export const MCRM_QUERY_CURRENT_USER = 'CURRENT_USER';
export const MCRM_QUERY_USER_ROLES = 'USER_ROLES';
export const MCRM_QUERY_ROLES = 'ROLES';