export const MCRM_ACCESS_TOKEN_KEY = 'MCRM_ACCESS_TOKEN';
export const MCRM_REFRESH_TOKEN_KEY = 'MCRM_REFRESH_TOKEN';
export const MCRM_DARK_MODE = 'MCRM_DARK_MODE';
export const MCRM_QUERY_KEY_USERS = 'USERS';
export const MCRM_QUERY_CURRENT_USER = 'CURRENT_USER';